sonar.projectKey=Kaju2002_CTSE_MicroService_event-service
sonar.organization=kaju2002
sonar.projectName=Event Service
sonar.sources=.
sonar.exclusions=node_modules/**,coverage/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
