services:
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "3001:3000"
    env_file:
      - ./user-service/.env
    depends_on:
      - postgres-user

  postgres-user:
    image: postgres:15
    container_name: postgres-user
    restart: always
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  review-service:
    build: ./review-service
    container_name: review-service
    ports:
      - "3002:3001"
    environment:
      MONGODB_URI: mongodb://mongo-review:27017/reviewdb
    depends_on:
      - mongo-review

  mongo-review:
    image: mongo:7
    container_name: mongo-review
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_review_data:/data/db

volumes:
  postgres_data:
  mongo_review_data: