sonar.projectKey=ctse_review_service
sonar.projectName=CTSE Review Service
sonar.projectVersion=1.0
sonar.organization=kaju2002
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=node_modules/**,**/*.test.js,**/dist/**
sonar.coverage.exclusions=node_modules/**,**/*.test.js
